language: python
dist: trusty
cache: false
python:
 - "3.6"
install: 
 - pip install -e .
 - pip install python-telegram-bot --upgrade
 - git submodule update --init --recursive
 - pip install pygame
script: pytest
